# Generated by Django 3.0.8 on 2020-08-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='exam_name',
            new_name='exams',
        ),
    ]
