# Generated by Django 3.0.8 on 2020-08-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200810_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='exams',
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.Teacher'),
            preserve_default=False,
        ),
    ]
