# Generated by Django 3.0.8 on 2020-08-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200810_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
