# Generated by Django 3.0.8 on 2020-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200905_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.FloatField(null=True),
        ),
    ]
