# Generated by Django 3.0.8 on 2020-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20201003_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_year',
            field=models.IntegerField(null=True),
        ),
    ]
