# Generated by Django 3.0.8 on 2020-10-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='exam.Student'),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='exam.Teacher'),
        ),
    ]
