# Generated by Django 3.1.4 on 2020-12-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20201217_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='student_scoreing',
            new_name='student_score',
        ),
    ]
