# Generated by Django 3.1.4 on 2020-12-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20201217_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_name', to='exam.exam'),
        ),
    ]
